---
driver_plugin: docker
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 256
    cpus: 2
platforms:
- name: debian-7.2.0
  driver_config:
    box: opscode-debian-7.2.0
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.2.0_chef-provisionerless.box
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
  run_list:
  - recipe[apt]
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-10.04_chef-provisionerless.box
  run_list:
  - recipe[apt]
- name: centos-6.5
  driver_config:
    box: opscode-centos-6.5
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box
suites:
- name: source_v41
  run_list:
    - recipe[zeromq]
  attributes:
    zeromq:
      version: v4.1.4
      src_url: https://github.com/zeromq/zeromq4-1.git
- name: source_v40
  run_list:
    - recipe[zeromq]
  attributes:
    zeromq:
      version: v4.0.7
      src_url: https://github.com/zeromq/zeromq4-x.git
- name: source_custom_dir
  run_list:
  - recipe[zeromq]
  attributes:
    zeromq:
      dir: /opt/zeromq
  includes: ["ubuntu-12.04"]
- name: package
  run_list:
    - recipe[zeromq]
  attributes:
    zeromq:
      install_method: package
  excludes: ["centos-6.5", "debian-6.0.8", "ubuntu-10.04"]
